/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import model.Mobil;
import utils.DatabaseConnection;
import utils.PrintMobil;
import dao.MobilDAO;
import java.awt.print.PrinterJob;
import java.awt.print.PrinterException;



public class TambahMobil extends javax.swing.JFrame {
    private MobilDAO mobilDAO;
    private DefaultTableModel tableModel;

    public TambahMobil(Connection connection) {
        this.mobilDAO = new MobilDAO(connection);
        initComponents();
        initTable();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaMobil = new javax.swing.JTextField();
        comboJenisMobil = new javax.swing.JComboBox<>();
        txtHargaPerHari = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMobil = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FORM DATA MOBIL");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nama Mobil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(28, 20, 7, 20);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Jenis Mobil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Harga Per Hari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(jLabel5, gridBagConstraints);

        txtNamaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMobilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(28, 20, 7, 20);
        jPanel2.add(txtNamaMobil, gridBagConstraints);

        comboJenisMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MPV", "Sedan", "SUV", "Truck" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(comboJenisMobil, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(txtHargaPerHari, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(btnTambah, gridBagConstraints);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(btnEdit, gridBagConstraints);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(btnHapus, gridBagConstraints);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel3.add(btnClear, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(jPanel3, gridBagConstraints);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(btnCetak, gridBagConstraints);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMobil);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 7, 20);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 0, 0);
        jPanel2.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void initTable() {
    String[] columns = {"ID", "Nama Mobil", "Jenis Mobil", "Harga Per Hari"};
    tableModel = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua sel tabel tidak bisa diedit
        }
    };
    tableMobil.setModel(tableModel);

    // Menambahkan MouseListener untuk menangkap event klik pada tabel
    tableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tableMobilMouseClicked(evt);
        }
    });
}

private void tableMobilMouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = tableMobil.getSelectedRow();
    if (selectedRow != -1) {
        // Ambil data dari baris yang dipilih
        String id = tableModel.getValueAt(selectedRow, 0).toString();
        String nama = tableModel.getValueAt(selectedRow, 1).toString();
        String jenis = tableModel.getValueAt(selectedRow, 2).toString();
        String harga = tableModel.getValueAt(selectedRow, 3).toString();

        // Isi text field
        txtNamaMobil.setText(nama);
        comboJenisMobil.setSelectedItem(jenis); // Pastikan item di combobox sesuai
        txtHargaPerHari.setText(harga);
    }
}
  
    private void loadTable() {
        tableModel.setRowCount(0); // Clear table
        try {
            List<Mobil> mobilList = mobilDAO.getAllMobil();
            for (Mobil mobil : mobilList) {
                Object[] row = {
                    mobil.getIdMobil(),
                    mobil.getNamaMobil(),
                    mobil.getJenisMobil(),
                    mobil.getHargaPerHari()
                };
                tableModel.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private boolean validateInputs() {
        if (txtNamaMobil.getText().isEmpty() || comboJenisMobil.getSelectedItem() == null || txtHargaPerHari.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        try {
            Double.parseDouble(txtHargaPerHari.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga Per Hari must be a number!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
          if (!validateInputs()) return;

        String nama = txtNamaMobil.getText();
        String jenis = comboJenisMobil.getSelectedItem().toString();
        double harga = Double.parseDouble(txtHargaPerHari.getText());

        Mobil mobil = new Mobil(0, nama, jenis, harga);
        try {
            mobilDAO.addMobil(mobil);
            JOptionPane.showMessageDialog(this, "Data added successfully!");
            loadTable();
            clearInputs();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtNamaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMobilActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     int selectedRow = tableMobil.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateInputs()) return;

        int id = (int) tableModel.getValueAt(selectedRow, 0);
        String nama = txtNamaMobil.getText();
        String jenis = comboJenisMobil.getSelectedItem().toString();
        double harga = Double.parseDouble(txtHargaPerHari.getText());

        Mobil mobil = new Mobil(id, nama, jenis, harga);
        try {
            mobilDAO.updateMobil(mobil);
            JOptionPane.showMessageDialog(this, "Data updated successfully!");
            loadTable();
            clearInputs();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    int selectedRow = tableMobil.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tableModel.getValueAt(selectedRow, 0);
        try {
            mobilDAO.deleteMobil(id);
            JOptionPane.showMessageDialog(this, "Data deleted successfully!");
            loadTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    clearInputs();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
    PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new PrintMobil(tableMobil));
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException e) {
                JOptionPane.showMessageDialog(TambahMobil.this, 
                    "Gagal mencetak: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnCetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose(); // Menutup form saat ini
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearInputs() {
        txtNamaMobil.setText("");
        comboJenisMobil.setSelectedIndex(-1);
        txtHargaPerHari.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        // Mendapatkan koneksi dari DatabaseConnection
        Connection connection = DatabaseConnection.getConnection();

        // Membuat instance MobilDAO
        MobilDAO mobilDAO = new MobilDAO(connection);

        // Membuat form TambahMobil dan mengirimkan koneksi
        new TambahMobil(connection).setVisible(true);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal terhubung ke database: " + e.getMessage(), 
                                      "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> comboJenisMobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMobil;
    private javax.swing.JTextField txtHargaPerHari;
    private javax.swing.JTextField txtNamaMobil;
    // End of variables declaration//GEN-END:variables
}
